coverage:
  ignore:
   - "Src/LibraryCore.Core/Properties/**"
   - "LibraryCore.Core/Properties/**"
   - "LibraryCore.Core/Properties/**"
  status:
    project:
      default:
      # basic
      target: auto
      threshold: 0%
      base: auto 
    patch:
      default:
        target: 0%
ignore:
  - "Src/LibraryCore.Core/Properties/**"
  - "LibraryCore.Core/Properties/**"
  - "LibraryCore.Core/Properties/**"
