# For more configuration details:
# https://docs.codecov.io/docs/codecov-yaml

# Check if this file is valid by running in bash:
# curl -X POST --data-binary @.codecov.yml https://codecov.io/validate
# Jason - use ubuntu terminal. While in current directory where teh .codecov.yml exists run "curl -X POST --data-binary @.codecov.yml https://codecov.io/validate"

# Coverage configuration
# ----------------------

coverage:
  status:
    patch: false

  range: 60..90     # First number represents red, and second represents green
                    # (default is 70..100)
  round: up       # up, down, or nearest
  precision: 1      # Number of decimal places, between 0 and 5

# Ignoring Paths
# --------------
# which folders/files to ignore
ignore:
   - "**/Resources.Designer.cs"
#  - "Src/LibraryCore.Core/Properties/*"

