version: "3.9"
services:
  sql-server:
      image: mcr.microsoft.com/mssql/server:2017-latest
      environment:
        - SA_PASSWORD=${DB_PW}
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PW}
    ports:
      - 27017:27017


  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
    # To learn about configuring Kafka for access across networks see
    # https://www.confluent.io/blog/kafka-client-cannot-connect-to-broker-on-aws-on-docker-etc/
      - "9092:9092"
      - "29092:29092"
      - "9093:9093"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092,PLAINTEXT_EXTERNAL://localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  #init-kafka:
  #  image: confluentinc/cp-kafka:7.0.1
  #  depends_on:
  #    - broker
  #  entrypoint: [ '/bin/sh', '-c' ]
  #  command: |
  #    "
  #    # blocks until kafka is reachable
  #    kafka-topics --bootstrap-server broker:29092 --list

  #    echo -e 'Creating kafka topics'
  #    kafka-topics --bootstrap-server broker:29092 --create --if-not-exists --topic my-topic-1 --replication-factor 1 --partitions 1

  #    echo -e 'Successfully created the following topics:'
  #    kafka-topics --bootstrap-server broker:29092 --list
  #    "

  #integration-tests:
  #  container_name: integration-tests
  #  image: mcr.microsoft.com/dotnet/sdk:${Dotnet_Version}
  #  environment:
  #    - Db_ConnectionString=Data Source=sql-server;Initial Catalog=IntegrationTest;User Id=sa;Password=${DB_PW};trustServerCertificate=true
  #  volumes:
  #    - .:/Src
  #  working_dir: /Src
  #  command:
  #    #[
  #    #  "dotnet",
  #    #  "test",
  #    #  "./IntegrationTests/LibraryCore.IntegrationTests/LibraryCore.IntegrationTests.csproj",
  #    #  "-c",
  #    #  "release",
  #    #  "-f",
  #    #  "net${Dotnet_Version}"
  #    #]
  #  depends_on:
  #    - sql-server
