version: "3.9"
services:
  sql-server:
      image: mcr.microsoft.com/mssql/server:2017-latest
      environment:
        - SA_PASSWORD=${DB_PW}
        - ACCEPT_EULA=Y
      ports:
        - "1433:1433"
  integration-tests:
    container_name: integration-tests
    image: mcr.microsoft.com/dotnet/sdk:${Dotnet_Version}
    environment:
      - Db_ConnectionString=Data Source=sql-server;Initial Catalog=IntegrationTest;User Id=sa;Password=${DB_PW};trustServerCertificate=true
    volumes:
      - .:/Src
    working_dir: /Src
    command:
      - dotnet nuget add source --username dibiancoj@gmail.com --password ${GH_TOKEN} --store-password-in-clear-text --name github https://nuget.pkg.github.com/dibiancoj/index.json
      - dotnet test ./IntegrationTests/LibraryCore.IntegrationTests/LibraryCore.IntegrationTests.csproj -c release -f net${Dotnet_Version}
    depends_on:
      - sql-server
