//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryCore.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibraryCore.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;states&quot;: [
        ///         {
        ///            &quot;id&quot;: &quot;AL&quot;,
        ///            &quot;description&quot;: &quot;Alabama&quot;
        ///         },
        ///         {
        ///            &quot;id&quot;: &quot;AK&quot;,
        ///            &quot;description&quot;: &quot;Alaska&quot;
        ///         },
        ///         {
        ///            &quot;id&quot;: &quot;AZ&quot;,
        ///            &quot;description&quot;: &quot;Arizona&quot;
        ///         },
        ///         {
        ///            &quot;id&quot;: &quot;AR&quot;,
        ///            &quot;description&quot;: &quot;Arkansas&quot;
        ///         },
        ///         {
        ///            &quot;id&quot;: &quot;CA&quot;,
        ///            &quot;description&quot;: &quot;California&quot;
        ///         },
        ///         {
        ///            &quot;id&quot;: &quot;CO&quot;,
        ///            &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnitedState_StateListing {
            get {
                return ResourceManager.GetString("UnitedState_StateListing", resourceCulture);
            }
        }
    }
}
