name: Update-Nuget-Packages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  corenuget:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Package The Build
      run:  dotnet pack --configuration Release
    - name: Push The Nuget Build
      run:  dotnet nuget push "**/*.nupkg" --source "https://nuget.pkg.github.com/dibiancoj/index.json" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
