name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --filter FullyQualifiedName!~LibraryCore.IntegrationTests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./Tests/LibraryCore.Tests.JsonNet/coverage.opencover.xml,./Tests/LibraryCore.Tests.Core/coverage.opencover.xml,./Tests/LibraryCore.Tests.AspNet/coverage.opencover.xml,./Tests/LibraryCore.Tests.CommandLineParser/coverage.opencover.xml # optional
        fail_ci_if_error: true # optional (default = false)

