name: Dotnet-Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 7.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x

    - name: Setup .NET 6.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --filter FullyQualifiedName!~LibraryCore.IntegrationTests --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      env:  #the env variables below fixes a .net 7 issue where the code coverage is json and doesn't get outputted right. These can be removed once they make a fix https://github.com/coverlet-coverage/coverlet/issues/1391
        CollectCoverage: true
        CoverletOutputFormat: opencover

    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        #files: "**/*.coverage.net7.0.opencover.xml"
        #haven't been able to get the blob pattern correct
        files: ./Tests/LibraryCore.Tests.JsonNet/coverage.net7.0.opencover.xml,./Tests/LibraryCore.Tests.Core/coverage.net7.0.opencover.xml,./Tests/LibraryCore.Tests.AspNet/coverage.net7.0.opencover.xml,./Tests/LibraryCore.Tests.CommandLineParser/coverage.net7.0.opencover.xml,./Tests/LibraryCore.Tests.AspNet.DistributedSessionState/coverage.net7.0.opencover.xml,./Tests/LibraryCore.Tests.AspNet.HtmlRendering/coverage.net7.0.opencover.xml # optional
        fail_ci_if_error: true # optional (default = false)

