name: Integration-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2

    - name: Prep Auth For NuGet
      run: dotnet nuget add source --username dibiancoj@gmail.com --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/dibiancoj/index.json"

    #- name: IntegrationTests_netcore6
    #  working-directory: ./IntegrationTests
    #  run: docker-compose up --exit-code-from integration-tests integration-tests
    #  env: 
    #    DB_PW: ${{secrets.IntegrationTestSqlPw}}
    #    Dotnet_Version: "6.0"

    - name: IntegrationTests_netcore7
      working-directory: ./IntegrationTests
      run: docker-compose up --exit-code-from integration-tests integration-tests
      env: 
        DB_PW: ${{secrets.IntegrationTestSqlPw}}
        Dotnet_Version: "7.0"
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}